[package]
name = "joels-caches"
version = "0.1.0"
authors = ["Joel Ellis <joel@ellis.link>"]
edition = "2018"
licence = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
